version: "3"

services:
  mysql:
    image: mysql
    hostname: mysql-container
    networks:
      mynetwork:
        ipv4_address: 172.20.1.4
    volumes:
      - mysql-data:/var/lib/mysql
    # ports:
      # - "9871:9870"

  hive:
    image: hive
    hostname: hive-container
    networks:
      mynetwork:
        ipv4_address: 172.20.1.2
    depends_on:
      - mysql
    volumes:
      - datanode-data:/home/hadoop/hdfs/datanode
      - namenode-data:/home/hadoop/hdfs/namenode
    ports:
      - "10009:10000"
      - "9871:9870"

  airflow:
    image: airflow
    hostname: airflow-container
    networks:
      mynetwork:
        ipv4_address: 172.20.1.3
    depends_on:
      - hive
    ports:
      - "8081:8080"

  superset:
    image: superset
    hostname: superset-container
    networks:
      mynetwork:
        ipv4_address: 172.20.1.5
    depends_on:
      - hive
    ports:
      - "8089:8088"

volumes:
  datanode-data:
  namenode-data:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/16